### ISSUE TITLE
How do you benchmark FBPINN and use MultiAdam

### ISSUE THREAD

**Issue by SimonZeng7108** [i207M/PINNacle#1]
Hello Authors,

Thank you for the hard work on the benchmarks.

The demo code did not include any benchmark using FBPINN on different cases nor utilised multiAdam. Can you provide more documentation, please?

Thank you.

Good luck with NIPs!

**Comment by i207M** [comment]
Hi,

Thanks for your interest. We've done the comparisons using FBPINN and MultiAdam. However, we're currently tidying up the code due to implementation differences. We'll update the documentation with these details soon.
