### ISSUE TITLE
ref data for hNd pNd

### ISSUE THREAD

**Issue by VhaoYan** [i207M/PINNacle#4]
Hi, could you please also provide your ref data for high dim?

**Comment by i207M** [comment]
Sure. Actually we've designed the two high-dimensional problems to have analytical solutions. Please refer to these two sections of code:
https://github.com/i207M/PINNacle/blob/d36c53f1c373fe1ad632a2a3b3e6ee978cbcfb79/src/pde/heat.py#L280C13-L280C20
https://github.com/i207M/PINNacle/blob/d36c53f1c373fe1ad632a2a3b3e6ee978cbcfb79/src/pde/poisson.py#L302C19-L302C19
Feel free to comment if you have additional questions.

**Comment by VhaoYan** [comment]
I was wondering: 
1: did you use the lbfgs alone, or adam_lbfgs for optimization? In your paper I found only states lbfgs. A bit confused.
2: is below the hyperparameters for all the equations? 
"[adam_param={'lr': 1e-3, 'betas': (0.9, 0.999)},  lbfgs_param={'lr': 1, 'max_iter': 20]"
or you've also optimized the hypers?
