### ISSUE TITLE
RAR interval argument vs log-every argument

### ISSUE THREAD

**Issue by svdcvt** [i207M/PINNacle#5]
Hello,
I am currently working on creating new sampling/resampling methods for PINNs. I decided to use your benchmark, because it has great number of PDEs and methods to compare!
However, I have already encountered many minor and major flaws in your code, because, of course, it is a very new work. And I am happy to help :) (i also hope that your work will be accepted for ICLR).

### Issue description

The main issue I encountering currently is about RAR-wrapper. I can't find myself the "root" or the inter-dependency of it, in order to correct the code. In becnhmark.py I change RAR parameter as:

```python
line 120: model.train = rar_wrapper(pde, model, {"interval": 10, "count": 1})
```
When I change argument `interval` to a number lower than `log-every`, the following error occurs:

```bash
$ python benchmark_fast.py --method rar --log-every 100 --device cpu
Using backend: pytorch

Set the default float type to float32
***** Begin #0-0 *****
Compiling model...
'compile' took 0.000140 s

PDE Class Name: Burgers1D
Training model...

Step      Train loss                        Test loss                         Test metric
0         [1.45e-02, 6.48e-01, 4.15e-02]    [1.58e-02, 6.48e-01, 4.15e-02]    []  
10        [4.48e-04, 4.10e-01, 1.98e-02]    [4.47e-04, 4.10e-01, 1.98e-02]    []  
Traceback (most recent call last):
  File "/home/dymchens-ext/PINNacle/benchmark_fast.py", line 149, in <module>
    trainer.train_all()
  File "/home/dymchens-ext/PINNacle/trainer.py", line 99, in train_all
    model.train(**train_args, model_save_path=save_path)
  File "/home/dymchens-ext/PINNacle/src/utils/rar.py", line 19, in wrapper
    train(*args, **kwargs)
  File "/home/dymchens-ext/PINNacle/deepxde/utils/internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
  File "/home/dymchens-ext/PINNacle/deepxde/model.py", line 603, in train
    self.callbacks.on_train_end()
  File "/home/dymchens-ext/PINNacle/deepxde/callbacks.py", line 94, in on_train_end
    callback.on_train_end()
  File "/home/dymchens-ext/PINNacle/src/utils/callbacks.py", line 208, in on_train_end
    self.frmses[:, 0], self.frmses[:, 1], self.frmses[:, 2]]).T,
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```
I guess it has to do with the fact, that wrapper changes `model` attribute `iterations` to interval, and therefore the callback `on_train_end` is called earlier than any logging was done, so there is no metrics calculated yet. I, though, don't know whether it is better to change the wrapper behaviour or the callbacks, or just to not log anything, or to restrict calculating default metrics (because, for example, I don't care about any except mse and residual). Currently, I just log every 10 iterations, and, of course, it is eating a lot of storage and as well logger is messy. In case of method i want to implement (writing a new wrapper, similar to rar), I have to, actually, update training data every iteration, so, my `--interval 1` argument is surely impossible to use without code correction.

Can you either direct me how to resolve this issue, and I can do merge commit for you, or maybe you have time to resolve it yourself so I can continue my work? Thanks in advance.

----------------------------------

#### Additional comments/questions (not connected to the issue).

Apart from this issue, I wanted to express few things (if needed, I can open issues, just tell me):
1) Argparse:
    - add to argparser of `benchmark.py` help comment for each argument, their usage and intentend values are not obvious without looking inside the code.
    - I think it is better if rar parameter interval and count are included in argparser. and I noticed that config.json doesn't save anything but iterations and log-every values (but maybe it is designed to be like this).
2) the "full documentation" website is lacking many descriptions, even when there is a subsection "header" in a content tree, but content item is not clickable (for example, RAR), but I gues you are aware of that.
3) weird one: if I would like to use `summary()` function from `src.utils.summary` standalone, deepxde uses tensorflow backend (at least the logger says so, and then I get error "no module tensorflow"), and there is no tensorflow in `requirements.txt` file... (I work in isolated environment with Nix, so it was easy to catch, but maybe it is not intended for user to use plot/summary functions).

4) RAR implementation and choice of RAR:
    - I am not sure that the algorithm is correctly implemented, as it doesn't have the sampling step (see screenshot below from [Wu et al., 2023] below), since the added points are from `X_train`:
![image](https://github.com/i207M/PINNacle/assets/24256366/95305c71-f151-4ae0-abb7-924409137fa7)
    - I am confused with the choice of RAR algorithm as the representative method for sampling method, as in [Wu et al., 2023] it shows worse quality compared to RAD or Random-R, can you explain your choice for me, please? 
    - I am, though, planning to implement several algorithms through deepXde as wrappers for PINNacle as I want to compare different resampling methods. Only thing I can't find, is there some script or option to run several methods and to have in the end some plot which compares loss for different methods or generates table similar to ones in your papers? Or script that collects `errors.txt` through `runs/`? I think this kind of benchmark script would be amazing. 

Thanks a lot in advance for your attention and possible answer. You can also reply me in email: sofya (dot) dymchenko -at- gmail com.

**Comment by i207M** [comment]
Sorry for the late response. It's been a hectic month for me. First, thanks for your interest in using our benchmark and digging into the implementation details to help. 

### Main issue

Your diagnosis is right. The reason is that, RAR is implemented by calling `train` multiple times, so multiple `on_train_end` as well. This can be fixed by modifying the callbacks so they don't produce outputs when there's no history. But I feel like there will be another issue that, once reached `log_every` epochs, each `train` call (for example every 10 epochs) will produce some outputs, which may be too much. So I suggest also checking `log_every` in `on_train_end` and if the last call is shorter than `log_every`, skip this run. What's your opinion?

### Other issues

Agree with things about argparse and docs.

The `summary` issue is related to DeepXDE which defaults to tensorflow. This will fix it

```
os.environ["DDEBACKEND"] = "pytorch"
```

~~I will check the RAR implementation issue later soon.~~ Yes, there is a mismatch between the algorithm and the implementation. The points should be sampled from the real domain instead of `X_train`. We will work out a fix for this.

Sorry we are unable to provide the exact scripts to generate table results, but you can find some useful functions in `scr/utils/plot.py` and `scr/utils/summary.py`.

Thank you once again and PRs are more than welcome.

**Comment by svdcvt** [comment]
Hi! Thanks for your reply.
In the end, I just wrote a callback for resampling. I also added other algorithms for adaptive sampling. I might do a pull-request at some point later when it is ready and proved to work (currently writing the paper). But you can check my fork for that.

**Comment by i207M** [comment]
That's great. Please do leave an arxiv link if available. Good luck with your paper!
