### ISSUE TITLE
Problem in quick test

### ISSUE THREAD

**Issue by shensummer** [i207M/PINNacle#7]
Hi, thanks for your great work. I'm trying to quikly test the code, and the following problem was presented. Can you tell me what's wrong with my code? Thank you very much.
![image](https://github.com/i207M/PINNacle/assets/110278041/e3de52de-49e6-4f3f-9783-68394ae47c8e)

**Comment by i207M** [comment]
I am assuming you are using Windows. The default encoding on Windows is GBK, yet our datasets are stored as UTF-8 text. Please run the code under Linux or check out this link https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html to specify encoding when np.loadtxt

**Comment by lihangshiwo** [comment]
Have you solved this problem please, I have the same problem in Windows and have tried modifying np.loadtxt

**Comment by i207M** [comment]
Does it still not work with encoding='utf-8' specified?

**Comment by lihangshiwo** [comment]
YES. I simply changed np.loadtxt(datapath, comments="%").asype(np.float32) to np.loadtxt(datapath, comments="%",encoding='utf8').asype(np.float32). This may be wrong or incomplete.

**Comment by i207M** [comment]
encoding='utf8'

**Comment by i207M** [comment]
Strange. Tested on my side:

Well, If that's the only problem, the quickest solution is to use an editor that can handle various encodings and save them as gbk encoding locally.

```
In [5]: np.loadtxt("burgers1d.dat",comments='%',encoding='utf8')
Out[5]:
array([[-1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.98      ,  0.06279012,  0.04759979, ...,  0.01789308,
         0.01650617,  0.01530819],
       [-0.96      ,  0.12533244,  0.09512083, ...,  0.03578516,
         0.03301159,  0.03061581],
       ...,
       [ 0.96      , -0.12533244, -0.09512083, ..., -0.03578516,
        -0.03301159, -0.03061581],
       [ 0.98      , -0.06279012, -0.04759979, ..., -0.01789308,
        -0.01650617, -0.01530819],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])
```

**Comment by shensummer** [comment]
Yes, your idea works. Thanks very much.
