### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by debrevitatevitae** [i207M/PINNacle#9]
PINNacle is getting quite some attention from the community!

To allow contributions and clarify reusability, it would be highly beneficial to include a license. See [here](https://choosealicense.com/).

**Comment by i207M** [comment]
Thank you for your suggestion and we have licensed our code under MIT. Hope you enjoy it. 60fc2d977067ed563a5fdf1d04a1679eba0ac59c

**Comment by debrevitatevitae** [comment]
Great news! Thanks for your effort
